# Generated by Django 3.0.2 on 2020-02-02 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ToDoApp', '0002_auto_20200202_1946'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='text',
            new_name='completed',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='item',
        ),
    ]
